management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8090
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    tomcat:
      initial-size: 1
  
application:
  policies:
    intersection: true
